Repository slavest/slavseat, pull requests merged in 2024-04, with the labels that each got.

#160 fix(backend): jwt cookie expire 지정
  apps/backend/src/libs/config/config.module.ts
  apps/backend/src/modules/auth/auth.controller.ts
  apps/backend/src/modules/jwt/jwt.service.ts
Labels: bug

#161 예약 관리 관련 리팩토링
  apps/frontend/package.json
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AddReserveForm.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/ExistReserveNotice.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/OverrideReserveConfirm.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/ReserveInfomation.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/Header.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/index.tsx
  apps/frontend/src/features/home/hooks/useReserveContext.ts
  apps/frontend/src/features/home/hooks/useReserveReducer.ts
  apps/frontend/src/features/home/providers/DrawerProvider.tsx
  apps/frontend/src/features/home/providers/ReserveProvider.tsx
  apps/frontend/src/features/home/routes/Home.tsx
  apps/frontend/src/shared/api/query/reserve/add-reserve.ts
  apps/frontend/src/shared/api/query/type.ts
  apps/frontend/src/shared/api/reserve.ts
  pnpm-lock.yaml
Labels: refactor

#162 고정석 유저 좌석 충돌 시 다른 컨텐츠 표기 & DateSelector 가시성 개선
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AddReserveForm.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AlwayUserNotice.tsx
  apps/frontend/src/features/home/hooks/useReserveReducer.ts
  apps/frontend/src/features/home/routes/Home.tsx
  apps/frontend/src/shared/components/DateSelector/components/DateItem.tsx
  apps/frontend/src/shared/components/DateSelector/index.tsx
Labels: enhancement

#163 통계 기능 추가
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/main.ts
  apps/backend/src/modules/statistics/dto/daily-statistics.dto.ts
  apps/backend/src/modules/statistics/dto/request/getStatisticsWithDateRange.dto.ts
  apps/backend/src/modules/statistics/statistics.controller.ts
  apps/backend/src/modules/statistics/statistics.module.ts
  apps/backend/src/modules/statistics/statistics.service.ts
  apps/frontend/dev-dist/sw.js
  apps/frontend/package.json
  apps/frontend/src/features/admin/components/Chart/RecentDailyReserveChart.tsx
  apps/frontend/src/features/admin/hooks/reserve-statistics.ts
  apps/frontend/src/features/admin/routes/AdminReserveStatistics.tsx
  apps/frontend/src/features/admin/routes/AdminRoot.tsx
  apps/frontend/src/features/reserve/hooks/useReserve.ts
  apps/frontend/src/main.tsx
  apps/frontend/src/shared/api/statistics.ts
  apps/frontend/src/shared/constants/location.constant.ts
  packages/types/src/model/index.ts
  packages/types/src/model/statistics.ts
  pnpm-lock.yaml
Labels: feature
