Repository slavest/slavseat, pull requests merged in 2024-05, with the labels that each got.

#136 Floor 순서 기능 추가, Floor 상세 수정 기능 추가
  apps/backend/src/modules/floor/dto/request/createFloorRequest.dto.ts
  apps/backend/src/modules/floor/dto/request/updateFloorRequest.dto.ts
  apps/backend/src/modules/floor/dto/request/updateFloorsRequest.dto.ts
  apps/backend/src/modules/floor/dto/response/updateFloorResponse.dto.ts
  apps/backend/src/modules/floor/entity/floor.entity.ts
  apps/backend/src/modules/floor/floor.controller.ts
  apps/backend/src/modules/floor/floor.service.ts
  apps/frontend/package.json
  apps/frontend/src/features/admin/components/DraggableTable/context.tsx
  apps/frontend/src/features/admin/components/DraggableTable/index.tsx
  apps/frontend/src/features/admin/components/DraggableTable/types.ts
  apps/frontend/src/features/admin/components/Dropdown/ManageFloorMenu.tsx
  apps/frontend/src/features/admin/components/Modal/EditFloorModal.tsx
  apps/frontend/src/features/admin/routes/AdminFloorManage.tsx
  apps/frontend/src/features/admin/utils/array.util.ts
  apps/frontend/src/main.tsx
  apps/frontend/src/shared/api/floor.ts
  apps/frontend/src/shared/api/query/floor/get-all-floor-summary.ts
  apps/frontend/src/shared/api/query/floor/update-floor.ts
  apps/frontend/src/shared/api/query/floor/update-floors.ts
  packages/types/src/model/floor.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#165 Floor 비활성화 상태 추가
  apps/backend/src/modules/floor/dto/request/createFloorRequest.dto.ts
  apps/backend/src/modules/floor/entity/floor.entity.ts
  apps/backend/src/modules/floor/floor.service.ts
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/src/features/admin/components/Modal/EditFloorModal.tsx
  apps/frontend/src/features/home/routes/Home.tsx
  packages/types/src/model/floor.ts
Labels: feature

#171 푸터 즐겨찾기 및 숏컷 버튼 제거, 프로필 페이지 수정, 버튼요소 cursor-pointer 추가 등
  apps/frontend/src/features/favorite/routes/Favorite.tsx
  apps/frontend/src/features/profile/routes/Profile.tsx
  apps/frontend/src/features/reserve/routes/Reserve.tsx
  apps/frontend/src/main.tsx
  apps/frontend/src/shared/components/AppFooter/index.tsx
  apps/frontend/src/shared/components/DateSelector/components/DateItem.tsx
  apps/frontend/src/shared/components/FacilityGridViewer/index.tsx
  apps/frontend/src/shared/components/Tab/index.tsx
  apps/frontend/src/shared/routes/Root.tsx
Labels: enhancement

#173 fix(frontend): 고정석 예약 제외, cursor-pointer 추가
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AddReserveForm.tsx
  apps/frontend/src/shared/components/FacilityGridViewer/index.tsx
  apps/frontend/src/shared/components/Toggle/components/Item.tsx
Labels: enhancement

#174 어드민 CSV 추가, 날짜 범위 검색
  .dockerignore
  .github/workflows/node-build-reuseable.yaml
  apps/backend/Dockerfile
  apps/backend/src/modules/reserve/dto/request/getReserveByRangeDateRequest.dto.ts
  apps/backend/src/modules/reserve/dto/response/getReserveByDateResponse.dto.ts
  apps/backend/src/modules/reserve/reserve.controller.ts
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/Dockerfile
  apps/frontend/package.json
  apps/frontend/src/features/admin/components/AdminHeader/index.tsx
  apps/frontend/src/features/admin/components/Box/index.tsx
  apps/frontend/src/features/admin/components/Dropdown/ManageReserveMenu.tsx
  apps/frontend/src/features/admin/components/ReserveExcelDownload/index.tsx
  apps/frontend/src/features/admin/hooks/cancel-reserve.ts
  apps/frontend/src/features/admin/routes/AdminFacilityEdit.tsx
  apps/frontend/src/features/admin/routes/AdminReserveManage.tsx
  apps/frontend/src/features/admin/routes/AdminRoot.tsx
  apps/frontend/src/shared/api/query/reserve/get-reserve-by-range-date.ts
  apps/frontend/src/shared/api/reserve.ts
  apps/frontend/src/shared/components/Table/index.tsx
  apps/frontend/src/shared/constants/date.constant.ts
  pnpm-lock.yaml
Labels: feature

#175 어드민 예약 범위 검색 & csv 추출
  .dockerignore
  .github/workflows/node-build-reuseable.yaml
  .github/workflows/semantic-release-reuseable.yaml
  apps/backend/Dockerfile
  apps/backend/src/modules/reserve/dto/request/getReserveByRangeDateRequest.dto.ts
  apps/backend/src/modules/reserve/dto/response/getReserveByDateResponse.dto.ts
  apps/backend/src/modules/reserve/reserve.controller.ts
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/Dockerfile
  apps/frontend/package.json
  apps/frontend/src/features/admin/components/AdminHeader/index.tsx
  apps/frontend/src/features/admin/components/Box/index.tsx
  apps/frontend/src/features/admin/components/Dropdown/ManageReserveMenu.tsx
  apps/frontend/src/features/admin/components/ReserveExcelDownload/index.tsx
  apps/frontend/src/features/admin/hooks/cancel-reserve.ts
  apps/frontend/src/features/admin/routes/AdminFacilityEdit.tsx
  apps/frontend/src/features/admin/routes/AdminReserveManage.tsx
  apps/frontend/src/features/admin/routes/AdminRoot.tsx
  apps/frontend/src/features/favorite/routes/Favorite.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AddReserveForm.tsx
  apps/frontend/src/features/profile/routes/Profile.tsx
  apps/frontend/src/features/reserve/routes/Reserve.tsx
  apps/frontend/src/main.tsx
  apps/frontend/src/shared/api/query/reserve/get-reserve-by-range-date.ts
  apps/frontend/src/shared/api/reserve.ts
  apps/frontend/src/shared/components/AppFooter/index.tsx
  apps/frontend/src/shared/components/DateSelector/components/DateItem.tsx
  apps/frontend/src/shared/components/FacilityGridViewer/index.tsx
  apps/frontend/src/shared/components/Tab/index.tsx
  apps/frontend/src/shared/components/Table/index.tsx
  apps/frontend/src/shared/components/Toggle/components/Item.tsx
  apps/frontend/src/shared/constants/date.constant.ts
  apps/frontend/src/shared/routes/Root.tsx
  package.json
  pnpm-lock.yaml
Labels: release

#180 데스크탑 사이즈 임시 제공!
  apps/frontend/src/features/home/components/SeatCounter/index.tsx
  apps/frontend/src/shared/components/DateSelector/index.tsx
  apps/frontend/src/shared/routes/Root.tsx
Labels: enhancement

#182 fix(frontend): 월, 일 순차 변경 -> 한번에 변경으로 수정
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AddReserveForm.tsx
Labels: bug
