Repository slavest/slavseat, pull requests merged in 2024-06, with the labels that each got.

#186 patch(frontend): viewer route 뷰어용 페이지 임시 추가
  apps/frontend/src/features/viewer/components/Refresh.tsx
  apps/frontend/src/features/viewer/routes/Viewer.tsx
  apps/frontend/src/main.tsx
  apps/frontend/src/shared/components/DateSelector/index.tsx
  apps/frontend/src/shared/constants/location.constant.ts
Labels: feature

#187 patch(frontend): CSV 깨진 데이터 수정
  apps/frontend/src/features/admin/components/ReserveExcelDownload/index.tsx
Labels: enhancement

#188 Release 240604
  apps/frontend/package.json
  apps/frontend/src/features/admin/components/ReserveExcelDownload/index.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AddReserveForm.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/AlwayUserNotice.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/ExistReserveNotice.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/OverrideReserveConfirm.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/DrawerContents/ReserveInfomation.tsx
  apps/frontend/src/features/home/components/ReserveDrawer/Header.tsx
  apps/frontend/src/features/home/routes/Home.tsx
  apps/frontend/src/features/reserve/components/CancelReserveDrawer.tsx
  apps/frontend/src/features/viewer/components/Refresh.tsx
  apps/frontend/src/features/viewer/routes/Viewer.tsx
  apps/frontend/src/main.tsx
  apps/frontend/src/shared/components/DateSelector/index.tsx
  apps/frontend/src/shared/components/Drawer/components/Backdrop.tsx
  apps/frontend/src/shared/components/Drawer/components/Body.tsx
  apps/frontend/src/shared/components/Drawer/components/DragBar.tsx
  apps/frontend/src/shared/components/Drawer/components/Popover.tsx
  apps/frontend/src/shared/components/Drawer/components/Root.tsx
  apps/frontend/src/shared/components/Drawer/components/Trigger.tsx
  apps/frontend/src/shared/components/Drawer/context.tsx
  apps/frontend/src/shared/components/Drawer/hooks/useDrawerContext.ts
  apps/frontend/src/shared/components/Drawer/index.tsx
  apps/frontend/src/shared/components/Drawer/utils/index.ts
  apps/frontend/src/shared/components/Drawer_legacy/index.tsx
  apps/frontend/src/shared/components/Portal/index.tsx
  apps/frontend/src/shared/components/Portal/util.ts
  apps/frontend/src/shared/components/Tab/index.tsx
  apps/frontend/src/shared/components/TimePicker/components/TimeSlider.tsx
  apps/frontend/src/shared/components/TimePicker/index.tsx
  apps/frontend/src/shared/constants/location.constant.ts
  apps/frontend/src/shared/utils/drag.util.ts
  pnpm-lock.yaml
Labels: release

#190 patch(frontend): 관리자 예약 조회 페이지 좌석 검색 기능 추가
  apps/frontend/src/features/admin/routes/AdminReserveManage.tsx
Labels: feature

#194 예약 정책 변경에 따른 로직 수정 등
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/src/features/home/routes/Home.tsx
Labels: enhancement

#195 Release 240614
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/src/features/home/routes/Home.tsx
Labels: release

#196 내 예약 현황 UI 변경
  apps/frontend/src/features/home/routes/Home.tsx
  apps/frontend/src/features/reserve/components/CancelReserveDrawer.tsx
  apps/frontend/src/features/reserve/components/NotData.tsx
  apps/frontend/src/features/reserve/components/ReserveList.tsx
  apps/frontend/src/features/reserve/routes/Reserve.tsx
  apps/frontend/src/features/reserve/utils/reserve.util.ts
Labels: enhancement

#198 어드민용 강제 예약 추가
  apps/backend/src/modules/reserve/reserve.controller.ts
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/src/features/reserve/hooks/useReserve.ts
  apps/frontend/src/features/reserve/routes/Reserve.tsx
Labels: enhancement

#199 Release 240619
  apps/backend/src/modules/reserve/reserve.controller.ts
  apps/backend/src/modules/reserve/reserve.service.ts
  apps/frontend/src/features/home/routes/Home.tsx
  apps/frontend/src/features/reserve/components/CancelReserveDrawer.tsx
  apps/frontend/src/features/reserve/components/NotData.tsx
  apps/frontend/src/features/reserve/components/ReserveList.tsx
  apps/frontend/src/features/reserve/hooks/useReserve.ts
  apps/frontend/src/features/reserve/routes/Reserve.tsx
  apps/frontend/src/features/reserve/utils/reserve.util.ts
Labels: release
